services:
  traefik:
    image: 'traefik:v3.3'
    container_name: 'traefik'
    restart: unless-stopped
    command:
      - '--api.insecure=false'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=rlaalsrb1111@naver.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - web

  blog:
    build: .
    image: blog:latest
    container_name: blog
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'

      - 'traefik.http.routers.blog.rule=Host(`un-defined.dev`) || Host(`www.un-defined.dev`)'
      - 'traefik.http.routers.blog.entrypoints=websecure'
      - 'traefik.http.routers.blog.tls.certresolver=myresolver'
      - 'traefik.http.services.blog.loadbalancer.server.port=3000'

      - 'traefik.http.routers.http-redirect.rule=Host(`un-defined.dev`) || Host(`www.un-defined.dev`)'
      - 'traefik.http.routers.http-redirect.entrypoints=web'
      - 'traefik.http.routers.http-redirect.middlewares=redirect-to-https'

      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true'

    networks:
      - web

networks:
  web:
    external: true
